### ISSUE TITLE
Key validation phase does not handle snake casing

### ISSUE THREAD

**Issue by kdawgwilk** [DivvyPayHQ/absinthe_federation#44]
@scottming Looks like the validation phase doesn't check for the snake case version?
```
#18 7.042 The @key "someId" does not exist in :my_object object.
#18 7.042 
#18 7.042 
#18 7.042     (absinthe 1.7.0) lib/absinthe/schema.ex:366: Absinthe.Schema.__after_compile__/2
#18 7.042     (stdlib 3.16.1) lists.erl:1267: :lists.foldl/3
#18 7.042     (elixir 1.13.0) lib/kernel/parallel_compiler.ex:346: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/7
```
Schema
```
object :my_object do
    key_fields("someId")

    field(:some_id, non_null(:string))
    ...
end
```

**Comment by scottming** [comment]
Yes, That's a bug. Also, I think we need to make this clear in the documentation that when the key field is a snake, the function of `_resolve_reference ` can only match the snake parameter. Although this is not very ergonomic

```elixir
    field :some_id, :id do

    field :_resolve_reference, :product do
      resolve(fn
        _, %{someId: some_id}, _ -> ...
    end, %{someId: some_id}, _ -> ...
```
